// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XFDemo2 {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XFDemo2.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ForwardButtonText {
            get {
                return ResourceManager.GetString("ForwardButtonText", resourceCulture);
            }
        }
        
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        internal static string MainHeaderLabelText {
            get {
                return ResourceManager.GetString("MainHeaderLabelText", resourceCulture);
            }
        }
        
        internal static string ContactButtonText {
            get {
                return ResourceManager.GetString("ContactButtonText", resourceCulture);
            }
        }
        
        internal static string Option5ButtonText {
            get {
                return ResourceManager.GetString("Option5ButtonText", resourceCulture);
            }
        }
        
        internal static string Option4ButtonText {
            get {
                return ResourceManager.GetString("Option4ButtonText", resourceCulture);
            }
        }
        
        internal static string Option3ButtonText {
            get {
                return ResourceManager.GetString("Option3ButtonText", resourceCulture);
            }
        }
        
        internal static string Option2ButtonText {
            get {
                return ResourceManager.GetString("Option2ButtonText", resourceCulture);
            }
        }
        
        internal static string Option1ButtonText {
            get {
                return ResourceManager.GetString("Option1ButtonText", resourceCulture);
            }
        }
        
        internal static string Option6ButtonText {
            get {
                return ResourceManager.GetString("Option6ButtonText", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Contacts_0 {
            get {
                return ResourceManager.GetString("Contacts.0", resourceCulture);
            }
        }
        
        internal static string Contacts_0_0 {
            get {
                return ResourceManager.GetString("Contacts.0.0", resourceCulture);
            }
        }
        
        internal static string Contacts_0_0_0_Tel {
            get {
                return ResourceManager.GetString("Contacts.0.0.0.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_0_0_1_Tel {
            get {
                return ResourceManager.GetString("Contacts.0.0.1.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_0_1 {
            get {
                return ResourceManager.GetString("Contacts.0.1", resourceCulture);
            }
        }
        
        internal static string Contacts_0_1_0_Tel {
            get {
                return ResourceManager.GetString("Contacts.0.1.0.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_0_1_1_Tel {
            get {
                return ResourceManager.GetString("Contacts.0.1.1.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_0_2 {
            get {
                return ResourceManager.GetString("Contacts.0.2", resourceCulture);
            }
        }
        
        internal static string Contacts_0_2_0_Tel {
            get {
                return ResourceManager.GetString("Contacts.0.2.0.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_0_2_1_Tel {
            get {
                return ResourceManager.GetString("Contacts.0.2.1.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_1 {
            get {
                return ResourceManager.GetString("Contacts.1", resourceCulture);
            }
        }
        
        internal static string Contacts_1_0 {
            get {
                return ResourceManager.GetString("Contacts.1.0", resourceCulture);
            }
        }
        
        internal static string Contacts_1_0_0_Tel {
            get {
                return ResourceManager.GetString("Contacts.1.0.0.Tel", resourceCulture);
            }
        }
        
        internal static string Contacts_1_0_1_Tel {
            get {
                return ResourceManager.GetString("Contacts.1.0.1.Tel", resourceCulture);
            }
        }
        
        internal static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        internal static string Option1_0_End {
            get {
                return ResourceManager.GetString("Option1.0.End", resourceCulture);
            }
        }
        
        internal static string Option1_1_Topic {
            get {
                return ResourceManager.GetString("Option1.1.Topic", resourceCulture);
            }
        }
        
        internal static string Option1_1_Topic_Text {
            get {
                return ResourceManager.GetString("Option1.1.Topic.Text", resourceCulture);
            }
        }
    }
}
